### ISSUE TITLE
Cannot find GLTF Validator

### ISSUE THREAD

**Issue by enzyme69** [TimvanScherpenzeel/gltf-to-usdz#3]
I am not actually very familiar with node.js, but I downloaded your github and run the command, but keep getting the same error:

```bash
192-168-1-4:gltf-to-usdz-master jimmygunawan$ node ./bin/gltf-to-usdz.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'gltf-validator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jimmygunawan/gltf-to-usdz-master/lib/index.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by enzyme69** [comment]
So... my solutions to have to run these first:
npm install --save gltf-validator
npm install --save argparse
npm install --save sharp

And I think the GLTF to USDZ conversion successful!

**Comment by TimvanScherpenzeel** [comment]
Correct, when you run `npm install` it will install the dependencies for you (the dependencies are mentioned in the `package.json`).
